# include:
#   local: "/.gitlab/pipelines/Bootstrap-Ansible-Hosts.gitlab-ci.yml"
stages:
  - lint

lint-ansible-playbook:
  stage: lint
  tags:
    - ansible
  before_script:
    - cd ansible/
    - ansible-galaxy collection install --requirements-file collections/requirements.yml --force
  script:
    - chmod +x lint.sh
    - ./lint.sh
