---
# tasks file for gitlab-runner registration
- name: Register Gitlab Runner (shell-executes)
  when: runner_token | default('', true) | trim != ''
  register: create_runner
  ansible.builtin.shell: |
    gitlab-runner register \
    --url "https://gitlab.com" \
    --non-interactive \
    --executor shell \
    --token "{{ runner_token }}" \
    --description "{{ runner_description }}" \
    --executor shell

# Print this message if the gitlab-ci registration token was not exported as env var
- name: Print msg
  when: create_runner.changed == false
  ansible.builtin.debug:
    msg:
      - => Registration token variable 'RUNNER_TOKEN' is not set. No runner was registered.
      - => export your token as `RUNNER_TOKEN=glrt-XXXXX` before executing this role.
