---
- name: Install common packages
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: true

- name: Remove /etc/motd file
  ansible.builtin.file:
    path: /etc/motd
    state: absent

- name: Add login info message
  ansible.builtin.blockinfile:
    block: "{{ lookup('ansible.builtin.file', '{{ role_path }}/files/login') }}"
    path: "{{ default_user_home }}/.bashrc"
    marker: "## {mark} ANSIBLE MANAGED BLOCK ##"
  no_log: true
