---
- name: Play for configuring [galaxy_testing]
  hosts: galaxy_testing
  become: true

  vars:
    nfs_share: ansible

  roles:
    - common
    - docker
    - gitlab_install_runner
    - nfs
    - docker_group
    - gitlab_register_runner
