---
- name: Play for configuring server [testing]
  hosts: testing
  become: true

  roles:
    - common
    - docker
    - gitlab_install_runner
    - gitlab_register_runner
    - nfs
    - docker_group
